export const Wsymb2Descriptions: Record<number, string> = {
  1: "Clear sky",
  2: "Nearly clear sky",
  3: "Variable cloudiness",
  4: "Halfclear sky",
  5: "Cloudy sky",
  6: "Overcast",
  7: "Fog",
  8: "Light rain showers",
  9: "Moderate rain showers",
  10: "Heavy rain showers",
  11: "Thunderstorm",
  12: "Light sleet showers",
  13: "Moderate sleet showers",
  14: "Heavy sleet showers",
  15: "Light snow showers",
  16: "Moderate snow showers",
  17: "Heavy snow showers",
  18: "Light rain",
  19: "Moderate rain",
  20: "Heavy rain",
  21: "Thunder",
  22: "Light sleet",
  23: "Moderate sleet",
  24: "Heavy sleet",
  25: "Light snowfall",
  26: "Moderate snowfall",
  27: "Heavy snowfall",
};

export const weatherCodeMapSmhi: Record<
  number,
  { description: string; symbol: string }
> = {
  1: { description: "Clear sky", symbol: "☀️" },
  2: { description: "Nearly clear sky", symbol: "🌤️" },
  3: { description: "Variable cloudiness", symbol: "🌥️" },
  4: { description: "Halfclear sky", symbol: "🌤️" },
  5: { description: "Cloudy sky", symbol: "☁️" },
  6: { description: "Overcast", symbol: "☁️" },
  7: { description: "Fog", symbol: "🌫️" },
  8: { description: "Light rain showers", symbol: "🌦️" },
  9: { description: "Moderate rain showers", symbol: "🌦️" },
  10: { description: "Heavy rain showers", symbol: "🌧️" },
  11: { description: "Thunderstorm", symbol: "⛈️" },
  12: { description: "Light sleet showers", symbol: "🌧️" },
  13: { description: "Moderate sleet showers", symbol: "🌧️" },
  14: { description: "Heavy sleet showers", symbol: "🌧️" },
  15: { description: "Light snow showers", symbol: "🌨️" },
  16: { description: "Moderate snow showers", symbol: "🌨️" },
  17: { description: "Heavy snow showers", symbol: "🌨️" },
  18: { description: "Light rain", symbol: "🌧️" },
  19: { description: "Moderate rain", symbol: "🌧️" },
  20: { description: "Heavy rain", symbol: "🌧️" },
  21: { description: "Thunder", symbol: "⛈️" },
  22: { description: "Light sleet", symbol: "🌧️" },
  23: { description: "Moderate sleet", symbol: "🌧️" },
  24: { description: "Heavy sleet", symbol: "🌧️" },
  25: { description: "Light snowfall", symbol: "🌨️" },
  26: { description: "Moderate snowfall", symbol: "🌨️" },
};
